### ISSUE TITLE
Need to change event from CONNECTED TO CONNECTING

### ISSUE THREAD

**Issue by plackettsj1** [arlohb/OctoPrint-EnergenieControl#1]
Hi,
I was reading through your code to help me produce a custom LightwaveRF on-off plugin for my MK3S+. I noticed that whilst the disconnect logic is sound - the connect logic is not. Without having read the octoprint code it looks like the Connected event fires after the printer is connected - which can't happen assuming its switched off before you start. I found a relatively recent additional event CONNECTING - I changed this in the connect code and it enabled me to have the printer switched off, then press connect on Octopring 1.7.3 - the printer switches on and connects.

Hope this of help
Cheers
Simon

**Comment by arlohb** [comment]
Thank you for this. My current code works for me only because the raspberry pi running octoprint is powering the printer a little bit through USB. This means it can connect before the main power is switched on. I will work on fixing this though as it shouldn't rely on this happening.
